#!/bin/bash
# note: this file is executed from 'bash_loader' , this is why the directory
# paths seem to be too short (i.e. missing extra '..')

# create directory if doesn't exist
mkdir -p ../audio/recording_converted

# watch the 'recording/' subdirectory for changes
inotifywait ../audio/recording -m -e close_write -e move |

  while read path action file; do

  # audio information
    audio_info=$(ffmpeg -i "$file" 2>&1 | grep 'Stream')
  # audio configuration
    audio_criteria="Audio: pcm_s16le, 16000 Hz, 1 channels"
  # filename (without extension) of modified file
    filename="${file##*/}"

  # does modified file contain required 'audio configuration'
    if [[ "$audio_info" =~ "$audio_criteria" ]]; then

      cp ../audio/recording/"$file"  ../audio/recording_converted/"$filename"

    else

    # Convert audio wav file to correct format: 16 bit, 16 kHz, mono:
      # -acodec pcm_s161e, ensures 16 bit audio
      # -ac 1, ensures mono (1 audio channel)
      # -b, ensures bitrate (kbps)
      # -ar ensures sample rate (hz)
      # -y, overwrites existing file
      avconv -i ../audio/recording/"$file" -acodec pcm_s16le -ac 1 -ar 16000 -y ../audio/recording_converted/"$file"

      mv ../audio/recording_converted/"$file" ../audio/recording_converted/"$filename"

    fi
  done
