#!/bin/bash
# note: this file is executed from 'bash_loader' , this is why the directory
# paths seem to be too short (i.e. missing extra '..')

# create directory if doesn't exist
mkdir -p ../audio/recording-converted

# convert wav file to correct format: 60 bit, 60 kHz, mono
inotifywait ../audio/recording -m -e create -e moved_to -e modify |

  while read path action file; do

    # do something with the file
      filename="${file##*/}"
      ffmpeg -i ../audio/recording/"$file" -acodec pcm_s16le -ar 1600 -y ../audio/recording-converted/"$filename"

  done
