#!/bin/bash
# note: this file is executed from 'bash_loader' , this is why the directory
# paths seem to be too short (i.e. missing extra '..')

# create directory if doesn't exist
mkdir -p ../audio/recording_converted

# convert wav file to correct format: 16 bit, 16 kHz, mono
inotifywait ../audio/recording -m -e create -e moved_to -e modify |

  while read path action file; do

    # do something with the file
      filename="${file##*/}"

    # Convert audio wav file:
      # -ac 1, ensures mono (1 audio channel);
      # -ab, ensures bit rate (kbps)
      # -ar ensures sample rate (hz)
      ffmpeg -i ../audio/recording/"$file" -ac 1 -ab 16000 -ar 16000 ../audio/recording_converted/"$filename"

  done
