#!/bin/bash
# note: this file is executed from 'bash_loader' , this is why the directory
# paths seem to be too short (i.e. missing extra '..')

# allow 'pocketsphinx_continuous' command
PATH=$PATH:/usr/local/bin
PATH=$PATH:/var/www/audio-analyzer/pocketsphinx/acoustic_models

# create directory if doesn't exist
mkdir -p ../audio/recording_text

# apply CMUSphinx on audio wav file
inotifywait ../audio/recording_converted -m -e create -e moved_to -e modify |

  while read path action file; do

    # do something with the file
      filename="${file%%.*}"
      pocketsphinx_continuous -infile ../audio/recording_converted/"$file" -hmm ../pocketsphinx/acoustic_models/en-us -lm ../pocketsphinx/acoustic_models/cmusphinx-5.0en-us.lm.dmp >| ../audio/recording_text/"$filename"

  done
