#!/bin/bash

# trace last execution of 'bash_loader'
set -x; exec > log/log_bash_loader 2>&1

# allow @(var) syntax
shopt -s extglob

# predetermined directories: haystack = ( ./@(directory1|directory2|directory3)/* )
haystack=(./@(audio)/*)
true "${haystack[@]}"

# execute scripts in 'haystack'
for file in "${haystack[@]}"; do  
 sh ./"$file" &
done
