#!/bin/bash
# note: this file is executed from 'bash_loader' , this is why the directory
# paths seem to be too short (i.e. missing extra '..')

# allow @(var) syntax
shopt -s extglob

# track execution of script
#set -x; exec > logs/log_bash_loader 2>&1

# directory list to ignore
haystack=( ../pocketsphinx/sphinxbase ../pocketsphinx/pocketsphinx ../pocketsphinx/sphinxtrain )

for dir in "${haystack[@]}"; do  

  # subshell: add local ignore rules
  (cd "$dir" && echo '*' >> .git/info/exclude)

done
